spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order?charsetEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379

    jedis:
      pool:
        max-active: 10
        max-idle: 12
        min-idle: 8


mybatis:
  mapper-locations: classpath:static/mapper/*.xml
  config-location: classpath:static/config/SqlMapConfig.xml

logging:
  level:
    com.pk.consistency.mapper: debug


